### ISSUE TITLE
Harvest entry without comment is not detected as match after syncing

### ISSUE THREAD

**Issue by mineralf** [mineralf/ng-harvest-jira-sync#5]
This issue started appearing after switching JIRA from a own hosted to the official cloud hosted JIRA.

The two synced Harvest entries should appear in one line with the created JIRA worklogs.

![Screenshot from 2019-12-18 17-04-22](https://user-images.githubusercontent.com/15786855/71881605-e5b21300-3132-11ea-89cd-f2c3aed382ab.png)

Workaround would be to always enter a comment in the Harvest entry as "NGDP-43: comment"

Probably the issue is somewhere near this line: https://github.com/mineralf/ng-harvest-jira-sync/blob/develop/src/app/timesheet/service/timesheet.service.ts#L147

**Comment by ralf-br** [comment]
Resolved with version 0.6.0
